import { useState } from 'react';
import { useNavigate } from 'react-router';
import { Plus, Pencil, Trash2, ShoppingBag, Sparkles, Globe, Image } from 'lucide-react';
import { toast } from 'sonner';
import type { Recipe } from '@bake-app/shared-types';
import {
  useRecipes,
  useDeleteRecipe,
  useCreateProduct,
  useGenerateRecipeFromUrl,
  useGenerateRecipeFromImage,
  useCreateRecipe,
} from '@bake-app/react/api-client';
import {
  PageContainer,
  DataTable,
  LoadingSpinner,
  Modal,
  useConfirmation,
  type TableColumn,
} from '@bake-app/react/ui';

export function RecipesPage() {
  const navigate = useNavigate();
  const { data: recipes, isLoading } = useRecipes();
  const deleteRecipe = useDeleteRecipe();
  const createProduct = useCreateProduct();
  const createRecipe = useCreateRecipe();
  const generateFromUrl = useGenerateRecipeFromUrl();
  const generateFromImage = useGenerateRecipeFromImage();
  const { confirm, ConfirmationDialog } = useConfirmation();

  const [aiDialogOpen, setAiDialogOpen] = useState(false);
  const [aiMode, setAiMode] = useState<'url' | 'image'>('url');
  const [aiUrl, setAiUrl] = useState('');
  const [aiImageBase64, setAiImageBase64] = useState('');
  const [aiImageName, setAiImageName] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);

  const openAiDialog = () => {
    setAiUrl('');
    setAiImageBase64('');
    setAiImageName('');
    setAiMode('url');
    setAiDialogOpen(true);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setAiImageName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      setAiImageBase64(result.split(',')[1]);
    };
    reader.readAsDataURL(file);
  };

  const handleAiGenerate = async () => {
    setAiGenerating(true);
    try {
      let recipeData: any;
      if (aiMode === 'url') {
        if (!aiUrl.trim()) { toast.error('Please enter a URL'); return; }
        recipeData = await generateFromUrl.mutateAsync({ url: aiUrl.trim() });
      } else {
        if (!aiImageBase64) { toast.error('Please upload an image'); return; }
        recipeData = await generateFromImage.mutateAsync({ imageBase64: aiImageBase64 });
      }
      const created = await createRecipe.mutateAsync({
        ...recipeData,
        isActive: true,
        yieldQuantity: recipeData.yieldQuantity || 1,
        yieldUnit: recipeData.yieldUnit || 'pcs',
      } as any);
      toast.success(`Recipe "${recipeData.name || 'New Recipe'}" generated by AI`);
      setAiDialogOpen(false);
      navigate(`/recipes/${created.id}`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'AI generation failed');
    } finally {
      setAiGenerating(false);
    }
  };

  const handleDelete = async (recipe: Recipe) => {
    const confirmed = await confirm(
      'Delete Recipe',
      `Are you sure you want to delete "${recipe.name}"? This action cannot be undone.`,
      { variant: 'danger', confirmText: 'Delete' },
    );
    if (!confirmed) return;
    try {
      await deleteRecipe.mutateAsync(recipe.id);
      toast.success('Recipe deleted');
    } catch {
      toast.error('Failed to delete recipe');
    }
  };

  const handleCreateMenuItem = async (recipe: Recipe) => {
    const confirmed = await confirm(
      'Create Menu Item',
      `Create a new menu item linked to recipe "${recipe.name}"?`,
      { confirmText: 'Create' },
    );
    if (!confirmed) return;
    try {
      await createProduct.mutateAsync({
        name: recipe.name,
        type: 'produced',
        price: recipe.costPerUnit * 2.5, // default markup
        costPrice: recipe.costPerUnit,
        recipeId: recipe.id,
        isActive: true,
      });
      toast.success('Menu item created from recipe');
    } catch {
      toast.error('Failed to create menu item');
    }
  };

  const columns: TableColumn[] = [
    { key: 'name', label: 'Name', sortable: true },
    {
      key: 'category',
      label: 'Category',
      sortable: true,
      render: (value: string) => {
        if (!value) return <span className="text-sm text-gray-300">&mdash;</span>;
        const label = value
          .replace(/_/g, ' ')
          .replace(/\b\w/g, (c) => c.toUpperCase());
        return (
          <span className="inline-flex items-center rounded-full border border-gray-200 bg-gray-50 px-2 py-0.5 text-xs font-medium text-gray-600">
            {label}
          </span>
        );
      },
    },
    {
      key: 'yieldQuantity',
      label: 'Yield',
      sortable: true,
      render: (value: number, row: Recipe) => (
        <span className="text-sm text-gray-700">
          {value} {row.yieldUnit}
        </span>
      ),
    },
    {
      key: 'costPerUnit',
      label: 'Cost / Unit',
      type: 'currency',
      sortable: true,
    },
    {
      key: 'currentVersion',
      label: 'Version',
      render: (value: number) => (
        <span className="font-mono text-xs text-gray-500">v{value}</span>
      ),
    },
    {
      key: 'isActive',
      label: 'Status',
      render: (value: boolean) => (
        <span
          className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${
            value
              ? 'border-green-200 bg-green-100 text-green-800'
              : 'border-gray-200 bg-gray-100 text-gray-600'
          }`}
        >
          {value ? 'Active' : 'Inactive'}
        </span>
      ),
    },
    {
      key: 'actions',
      label: 'Actions',
      type: 'actions',
      sortable: false,
      width: '140px',
      actions: [
        {
          action: 'edit',
          icon: <Pencil size={16} />,
          tooltip: 'Edit recipe',
          onClick: (row: Recipe) => navigate(`/recipes/${row.id}`),
        },
        {
          action: 'create-product',
          icon: <ShoppingBag size={16} />,
          tooltip: 'Create menu item',
          color: 'text-blue-400 hover:text-blue-600',
          onClick: (row: Recipe) => handleCreateMenuItem(row),
        },
        {
          action: 'delete',
          icon: <Trash2 size={16} />,
          tooltip: 'Delete',
          color: 'text-red-400 hover:text-red-600',
          onClick: (row: Recipe) => handleDelete(row),
        },
      ],
    },
  ];

  return (
    <PageContainer
      title="Recipes"
      subtitle="Manage your bakery recipes"
      actions={
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={openAiDialog}
            className="flex items-center gap-2 rounded-lg border border-purple-200 bg-purple-50 px-4 py-2 text-sm font-medium text-purple-700 transition-all hover:bg-purple-100 active:scale-95"
          >
            <Sparkles size={16} />
            AI Generate
          </button>
          <button
            type="button"
            onClick={() => navigate('/recipes/new')}
            className="flex items-center gap-2 rounded-lg bg-[#8b4513] px-4 py-2 text-sm font-medium text-white transition-all hover:bg-[#5d4037] active:scale-95"
          >
            <Plus size={16} />
            Add Recipe
          </button>
        </div>
      }
    >
      {isLoading ? (
        <LoadingSpinner message="Loading recipes..." />
      ) : (
        <DataTable
          columns={columns}
          data={recipes ?? []}
          searchable
          searchPlaceholder="Search recipes..."
          pageSize={25}
        />
      )}

      {ConfirmationDialog}

      {/* AI Generate Dialog */}
      <Modal
        open={aiDialogOpen}
        onClose={() => !aiGenerating && setAiDialogOpen(false)}
        title="AI Recipe Generator"
        size="md"
        footer={
          <>
            <button
              type="button"
              onClick={() => setAiDialogOpen(false)}
              disabled={aiGenerating}
              className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 transition-all hover:bg-gray-50 disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleAiGenerate}
              disabled={aiGenerating || (aiMode === 'url' ? !aiUrl.trim() : !aiImageBase64)}
              className="flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-sm font-medium text-white transition-all hover:bg-purple-700 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Sparkles size={16} className={aiGenerating ? 'animate-spin' : ''} />
              {aiGenerating ? 'Generating...' : 'Generate Recipe'}
            </button>
          </>
        }
      >
        <p className="mb-4 text-sm text-gray-500">
          Use AI to automatically create a recipe from a URL or a photo of a recipe.
        </p>

        {/* Mode Tabs */}
        <div className="mb-4 flex rounded-lg border border-gray-200 p-0.5">
          <button
            type="button"
            onClick={() => setAiMode('url')}
            className={`flex flex-1 items-center justify-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-all ${
              aiMode === 'url'
                ? 'bg-purple-100 text-purple-700'
                : 'text-gray-500 hover:text-gray-700'
            }`}
          >
            <Globe size={16} />
            From URL
          </button>
          <button
            type="button"
            onClick={() => setAiMode('image')}
            className={`flex flex-1 items-center justify-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-all ${
              aiMode === 'image'
                ? 'bg-purple-100 text-purple-700'
                : 'text-gray-500 hover:text-gray-700'
            }`}
          >
            <Image size={16} />
            From Image
          </button>
        </div>

        {aiMode === 'url' ? (
          <div>
            <label className="mb-1 block text-sm font-medium text-[#5d4037]">
              Recipe URL
            </label>
            <input
              type="url"
              value={aiUrl}
              onChange={(e) => setAiUrl(e.target.value)}
              placeholder="https://www.example.com/recipe/..."
              className="w-full rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm focus:border-purple-400 focus:bg-white focus:outline-none focus:ring-1 focus:ring-purple-400/30"
              autoFocus
            />
            <p className="mt-1.5 text-xs text-gray-400">
              Paste a link to any recipe page. AI will extract the name, ingredients, instructions, and more.
            </p>
          </div>
        ) : (
          <div>
            <label className="mb-1 block text-sm font-medium text-[#5d4037]">
              Recipe Image
            </label>
            <label className="flex cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-gray-200 bg-gray-50 px-4 py-8 text-center transition-colors hover:border-purple-300 hover:bg-purple-50/30">
              <Image size={32} className="mb-2 text-gray-300" />
              {aiImageName ? (
                <span className="text-sm font-medium text-[#3e2723]">{aiImageName}</span>
              ) : (
                <span className="text-sm text-gray-400">Click to upload a photo</span>
              )}
              <span className="mt-1 text-xs text-gray-400">JPG, PNG, or WEBP</span>
              <input
                type="file"
                accept="image/*"
                onChange={handleImageUpload}
                className="hidden"
              />
            </label>
            <p className="mt-1.5 text-xs text-gray-400">
              Upload a photo of a recipe card, cookbook page, or handwritten recipe.
            </p>
          </div>
        )}
      </Modal>
    </PageContainer>
  );
}
